db:
  image: mohansai05/temp2:db

  environment:
    MYSQL_ROOT_PASSWORD: root123
    MYSQL_DATABASE: flaskdb
    MYSQL_USER: flaskuser
    MYSQL_PASSWORD: flaskpass

  deploy:
    replicas: 1
    restart_policy:
      condition: on-failure

  volumes:
    - db-data:/var/lib/mysql

  networks:
    - app-network
